sudo: requried

language: generic

sevices:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t chung1306/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true chung1306/docker-react-app npm run test -- --coverage # coverage: 자세하게 보여짐

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: Dockerreactapp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-152751511723
  bucket_path: docker-react-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY # travis settings에 환경설정으로 넣어둠
  secret_access_key: $AWS_SECRET_ACCESS_KEY